In [1]:
import numpy as np
import pandas as pd

In [2]:
arr = np.random.randint(10,size=(5,5))
arr

array([[1, 9, 2, 2, 7],
       [8, 0, 5, 4, 5],
       [2, 8, 1, 2, 2],
       [2, 8, 2, 4, 9],
       [7, 3, 9, 0, 1]])

In [3]:
df = pd.DataFrame(arr)
df

   0  1  2  3  4
0  1  9  2  2  7
1  8  0  5  4  5
2  2  8  1  2  2
3  2  8  2  4  9
4  7  3  9  0  1

In [4]:
df[0]

0    1
1    8
2    2
3    2
4    7
Name: 0, dtype: int64

In [5]:
df[df[0]>3]

   0  1  2  3  4
1  8  0  5  4  5
4  7  3  9  0  1

In [6]:
df.describe()

             0         1         2        3        4
count  5.00000  5.000000  5.000000  5.00000  5.00000
mean   4.00000  5.600000  3.800000  2.40000  4.80000
std    3.24037  3.911521  3.271085  1.67332  3.34664
min    1.00000  0.000000  1.000000  0.00000  1.00000
25%    2.00000  3.000000  2.000000  2.00000  2.00000
50%    2.00000  8.000000  2.000000  2.00000  5.00000
75%    7.00000  8.000000  5.000000  4.00000  7.00000
max    8.00000  9.000000  9.000000  4.00000  9.00000

In [7]:
df[1].describe()

count    5.000000
mean     5.600000
std      3.911521
min      0.000000
25%      3.000000
50%      8.000000
75%      8.000000
max      9.000000
Name: 1, dtype: float64

In [8]:
df[2].max()

9

In [9]:
df.isna()

       0      1      2      3      4
0  False  False  False  False  False
1  False  False  False  False  False
2  False  False  False  False  False
3  False  False  False  False  False
4  False  False  False  False  False

In [10]:
MyData = pd.read_csv("./indian_food.csv")
MyData

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45,25,sweet,dessert,West Bengal,East
1,Boondi,"Gram flour, ghee, sugar",vegetarian,80,30,sweet,dessert,Rajasthan,West
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15,60,sweet,dessert,Punjab,North
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15,30,sweet,dessert,Rajasthan,West
4,Gulab jamun,"Milk powder, plain flour, baking powder, ghee,...",vegetarian,15,40,sweet,dessert,West Bengal,East
...,...,...,...,...,...,...,...,...,...
250,Til Pitha,"Glutinous rice, black sesame seeds, gur",vegetarian,5,30,sweet,dessert,Assam,North East
251,Bebinca,"Coconut milk, egg yolks, clarified butter, all...",vegetarian,20,60,sweet,dessert,Goa,West
252,Shufta,"Cottage cheese, dry dates, dried rose petals, ...",vegetarian,-1,-1,sweet,dessert,Jammu & Kashmir,North
253,Mawa Bati,"Milk powder, dry fruits, arrowroot powder, all...",vegetarian,20,45,sweet,dessert,Madhya Pradesh,Central
254,Pinaca,"Brown rice, fennel seeds, grated coconut, blac...",vegetarian,-1,-1,sweet,dessert,Goa,West

In [11]:
MyData.head()
MyData.tail()

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
250,Til Pitha,"Glutinous rice, black sesame seeds, gur",vegetarian,5,30,sweet,dessert,Assam,North East
251,Bebinca,"Coconut milk, egg yolks, clarified butter, all...",vegetarian,20,60,sweet,dessert,Goa,West
252,Shufta,"Cottage cheese, dry dates, dried rose petals, ...",vegetarian,-1,-1,sweet,dessert,Jammu & Kashmir,North
253,Mawa Bati,"Milk powder, dry fruits, arrowroot powder, all...",vegetarian,20,45,sweet,dessert,Madhya Pradesh,Central
254,Pinaca,"Brown rice, fennel seeds, grated coconut, blac...",vegetarian,-1,-1,sweet,dessert,Goa,West

In [12]:
MyData.describe()

        prep_time   cook_time
count  255.000000  255.000000
mean    31.105882   34.529412
std     72.554409   48.265650
min     -1.000000   -1.000000
25%     10.000000   20.000000
50%     10.000000   30.000000
75%     20.000000   40.000000
max    500.000000  720.000000

In [13]:
MyData.shape

(255, 9)

In [14]:
MyData.head()

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45,25,sweet,dessert,West Bengal,East
1,Boondi,"Gram flour, ghee, sugar",vegetarian,80,30,sweet,dessert,Rajasthan,West
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15,60,sweet,dessert,Punjab,North
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15,30,sweet,dessert,Rajasthan,West
4,Gulab jamun,"Milk powder, plain flour, baking powder, ghee,...",vegetarian,15,40,sweet,dessert,West Bengal,East

In [15]:
MyData.isna().sum()

name              0
ingredients       0
diet              0
prep_time         0
cook_time         0
flavor_profile    0
course            0
state             0
region            1
dtype: int64

In [16]:
MyData["region"][MyData["region"].isna()]

110    NaN
Name: region, dtype: object

In [17]:
MyData["region"][105:111]

105    North
106    North
107    North
108    North
109       -1
110      NaN
Name: region, dtype: object

In [80]:
df = pd.read_csv("./Test2.csv")

In [72]:
df.head(12)

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45.0,25.0,sweet,dessert,West Bengal,East
1,Boondi,"Gram flour, ghee, sugar",vegetarian,80.0,30.0,NaN,dessert,Rajasthan,West
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15.0,60.0,sweet,dessert,Punjab,North
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15.0,30.0,sweet,dessert,Rajasthan,West
4,Gulab jamun,"Milk powder, plain flour, baking powder, ghee,...",vegetarian,15.0,NaN,sweet,dessert,West Bengal,East
5,Imarti,"Sugar syrup, lentil flour",vegetarian,NaN,50.0,NaN,dessert,West Bengal,East
6,Jalebi,"Maida, corn flour, baking soda, vinegar, curd,...",vegetarian,10.0,50.0,sweet,dessert,Uttar Pradesh,North
7,Kaju katli,"Cashews, ghee, cardamom, sugar",NaN,10.0,NaN,sweet,dessert,-1,-1
8,Kalakand,"Milk, cottage cheese, sugar",vegetarian,20.0,30.0,NaN,dessert,West Bengal,East
9,Kheer,"Milk, rice, sugar, dried fruits",vegetarian,10.0,40.0,sweet,dessert,-1,-1
10,Laddu,"Gram flour, ghee, sugar",vegetarian,10.0,40.0,sweet,dessert,-1,-1
11,Lassi,"Yogurt, milk, nuts, sugar",vegetarian,5.0,5.0,sweet,dessert,Punjab,North

In [73]:
df.isna().sum()

name              0
ingredients       0
diet              1
prep_time         1
cook_time         2
flavor_profile    3
course            0
state             0
region            0
dtype: int64

In [74]:
df["cook_time"]

0     25.0
1     30.0
2     60.0
3     30.0
4      NaN
5     50.0
6     50.0
7      NaN
8     30.0
9     40.0
10    40.0
11     5.0
12    30.0
Name: cook_time, dtype: float64

In [75]:
df["cook_time"].dropna(inplace= True)

In [76]:
print(df['cook_time'].dtype)

float64

In [77]:
print(df['cook_time'].isna().any())

True

In [78]:
df.dropna(subset=['cook_time'], inplace=True)

In [81]:
df

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45.0,25.0,sweet,dessert,West Bengal,East
1,Boondi,"Gram flour, ghee, sugar",vegetarian,80.0,30.0,NaN,dessert,Rajasthan,West
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15.0,60.0,sweet,dessert,Punjab,North
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15.0,30.0,sweet,dessert,Rajasthan,West
4,Gulab jamun,"Milk powder, plain flour, baking powder, ghee,...",vegetarian,15.0,NaN,sweet,dessert,West Bengal,East
5,Imarti,"Sugar syrup, lentil flour",vegetarian,NaN,50.0,NaN,dessert,West Bengal,East
6,Jalebi,"Maida, corn flour, baking soda, vinegar, curd,...",vegetarian,10.0,50.0,sweet,dessert,Uttar Pradesh,North
7,Kaju katli,"Cashews, ghee, cardamom, sugar",NaN,10.0,NaN,sweet,dessert,-1,-1
8,Kalakand,"Milk, cottage cheese, sugar",vegetarian,20.0,30.0,NaN,dessert,West Bengal,East
9,Kheer,"Milk, rice, sugar, dried fruits",vegetarian,10.0,40.0,sweet,dessert,-1,-1
10,Laddu,"Gram flour, ghee, sugar",vegetarian,10.0,40.0,sweet,dessert,-1,-1
11,Lassi,"Yogurt, milk, nuts, sugar",vegetarian,5.0,5.0,sweet,dessert,Punjab,North
12,Nankhatai,"Refined flour, besan, ghee, powdered sugar, yo...",vegetarian,20.0,30.0,sweet,dessert,-1,-1

In [86]:
df["cook_time"].isna().any()

True

In [89]:
df["cook_time"].mean()

35.45454545454545

In [93]:
df["cook_time"].fillna(df["cook_time"].mean(), inplace=True)

In [96]:
pd.to_datetime(df["cook_time"])

0    1970-01-01 00:00:00.000000025
1    1970-01-01 00:00:00.000000030
2    1970-01-01 00:00:00.000000060
3    1970-01-01 00:00:00.000000030
4    1970-01-01 00:00:00.000000035
5    1970-01-01 00:00:00.000000050
6    1970-01-01 00:00:00.000000050
7    1970-01-01 00:00:00.000000035
8    1970-01-01 00:00:00.000000030
9    1970-01-01 00:00:00.000000040
10   1970-01-01 00:00:00.000000040
11   1970-01-01 00:00:00.000000005
12   1970-01-01 00:00:00.000000030
Name: cook_time, dtype: datetime64[ns]

In [97]:
df["cook_time"]

0     25.000000
1     30.000000
2     60.000000
3     30.000000
4     35.454545
5     50.000000
6     50.000000
7     35.454545
8     30.000000
9     40.000000
10    40.000000
11     5.000000
12    30.000000
Name: cook_time, dtype: float64

In [98]:
df.loc[2, 'cook_time'] = 45

In [99]:
df

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45.0,25.000000,sweet,dessert,West Bengal,East
1,Boondi,"Gram flour, ghee, sugar",vegetarian,80.0,30.000000,NaN,dessert,Rajasthan,West
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15.0,45.000000,sweet,dessert,Punjab,North
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15.0,30.000000,sweet,dessert,Rajasthan,West
4,Gulab jamun,"Milk powder, plain flour, baking powder, ghee,...",vegetarian,15.0,35.454545,sweet,dessert,West Bengal,East
5,Imarti,"Sugar syrup, lentil flour",vegetarian,NaN,50.000000,NaN,dessert,West Bengal,East
6,Jalebi,"Maida, corn flour, baking soda, vinegar, curd,...",vegetarian,10.0,50.000000,sweet,dessert,Uttar Pradesh,North
7,Kaju katli,"Cashews, ghee, cardamom, sugar",NaN,10.0,35.454545,sweet,dessert,-1,-1
8,Kalakand,"Milk, cottage cheese, sugar",vegetarian,20.0,30.000000,NaN,dessert,West Bengal,East
9,Kheer,"Milk, rice, sugar, dried fruits",vegetarian,10.0,40.000000,sweet,dessert,-1,-1
10,Laddu,"Gram flour, ghee, sugar",vegetarian,10.0,40.000000,sweet,dessert,-1,-1
11,Lassi,"Yogurt, milk, nuts, sugar",vegetarian,5.0,5.000000,sweet,dessert,Punjab,North
12,Nankhatai,"Refined flour, besan, ghee, powdered sugar, yo...",vegetarian,20.0,30.000000,sweet,dessert,-1,-1

In [103]:
for x in df.index:
    if df.loc[x, 'cook_time'] > 35:
        df.loc[x, 'cook_time'] = 30

In [107]:
df.duplicated().any()

False

In [108]:
df.drop_duplicates(inplace=True)
df

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45.0,25.0,sweet,dessert,West Bengal,East
1,Boondi,"Gram flour, ghee, sugar",vegetarian,80.0,30.0,NaN,dessert,Rajasthan,West
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15.0,30.0,sweet,dessert,Punjab,North
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15.0,30.0,sweet,dessert,Rajasthan,West
4,Gulab jamun,"Milk powder, plain flour, baking powder, ghee,...",vegetarian,15.0,30.0,sweet,dessert,West Bengal,East
5,Imarti,"Sugar syrup, lentil flour",vegetarian,NaN,30.0,NaN,dessert,West Bengal,East
6,Jalebi,"Maida, corn flour, baking soda, vinegar, curd,...",vegetarian,10.0,30.0,sweet,dessert,Uttar Pradesh,North
7,Kaju katli,"Cashews, ghee, cardamom, sugar",NaN,10.0,30.0,sweet,dessert,-1,-1
8,Kalakand,"Milk, cottage cheese, sugar",vegetarian,20.0,30.0,NaN,dessert,West Bengal,East
9,Kheer,"Milk, rice, sugar, dried fruits",vegetarian,10.0,30.0,sweet,dessert,-1,-1
10,Laddu,"Gram flour, ghee, sugar",vegetarian,10.0,30.0,sweet,dessert,-1,-1
11,Lassi,"Yogurt, milk, nuts, sugar",vegetarian,5.0,5.0,sweet,dessert,Punjab,North
12,Nankhatai,"Refined flour, besan, ghee, powdered sugar, yo...",vegetarian,20.0,30.0,sweet,dessert,-1,-1

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            13 non-null     object
 1   ingredients     13 non-null     object
 2   diet            12 non-null     object
 3   prep_time       12 non-null     float64
 4   cook_time       13 non-null     float64
 5   flavor_profile  10 non-null     object
 6   course          13 non-null     object
 7   state           13 non-null     object
 8   region          13 non-null     object
dtypes: float64(2), object(7)
memory usage: 1.0+ KB

In [110]:
df

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45.0,25.0,sweet,dessert,West Bengal,East
1,Boondi,"Gram flour, ghee, sugar",vegetarian,80.0,30.0,NaN,dessert,Rajasthan,West
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15.0,30.0,sweet,dessert,Punjab,North
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15.0,30.0,sweet,dessert,Rajasthan,West
4,Gulab jamun,"Milk powder, plain flour, baking powder, ghee,...",vegetarian,15.0,30.0,sweet,dessert,West Bengal,East
5,Imarti,"Sugar syrup, lentil flour",vegetarian,NaN,30.0,NaN,dessert,West Bengal,East
6,Jalebi,"Maida, corn flour, baking soda, vinegar, curd,...",vegetarian,10.0,30.0,sweet,dessert,Uttar Pradesh,North
7,Kaju katli,"Cashews, ghee, cardamom, sugar",NaN,10.0,30.0,sweet,dessert,-1,-1
8,Kalakand,"Milk, cottage cheese, sugar",vegetarian,20.0,30.0,NaN,dessert,West Bengal,East
9,Kheer,"Milk, rice, sugar, dried fruits",vegetarian,10.0,30.0,sweet,dessert,-1,-1
10,Laddu,"Gram flour, ghee, sugar",vegetarian,10.0,30.0,sweet,dessert,-1,-1
11,Lassi,"Yogurt, milk, nuts, sugar",vegetarian,5.0,5.0,sweet,dessert,Punjab,North
12,Nankhatai,"Refined flour, besan, ghee, powdered sugar, yo...",vegetarian,20.0,30.0,sweet,dessert,-1,-1

In [111]:
df.dropna()

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45.0,25.0,sweet,dessert,West Bengal,East
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15.0,30.0,sweet,dessert,Punjab,North
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15.0,30.0,sweet,dessert,Rajasthan,West
4,Gulab jamun,"Milk powder, plain flour, baking powder, ghee,...",vegetarian,15.0,30.0,sweet,dessert,West Bengal,East
6,Jalebi,"Maida, corn flour, baking soda, vinegar, curd,...",vegetarian,10.0,30.0,sweet,dessert,Uttar Pradesh,North
9,Kheer,"Milk, rice, sugar, dried fruits",vegetarian,10.0,30.0,sweet,dessert,-1,-1
10,Laddu,"Gram flour, ghee, sugar",vegetarian,10.0,30.0,sweet,dessert,-1,-1
11,Lassi,"Yogurt, milk, nuts, sugar",vegetarian,5.0,5.0,sweet,dessert,Punjab,North
12,Nankhatai,"Refined flour, besan, ghee, powdered sugar, yo...",vegetarian,20.0,30.0,sweet,dessert,-1,-1

In [114]:
df.to_csv("./Result2.csv", index=True)